const TOKEN =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJEYW1pbG9sYSIsImlhdCI6MTcyOTcwNjcwMCwiZXhwIjoxNzYxODQ3NTAwLCJhdWQiOiJ3d3cuZGFtaWxvbGEuY29tIiwic3ViIjoiRGFtaWxvbGFAZGFtaWxvbGEuY29tIiwiR2l2ZW5OYW1lIjoiSm9obm55IiwiU3VybmFtZSI6IlJvY2tldCIsIkVtYWlsIjoianJvY2tldEBleGFtcGxlLmNvbSIsIlJvbGUiOlsiTWFuYWdlciIsIlByb2plY3QgQWRtaW5pc3RyYXRvciJdfQ.AejyrXm7nd_xUQ7-h9zZc_kMtTrNTgdkuA_ZLxw3P1U";

module.exports = TOKEN;
